spring:
  application:
    name: gandalf

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}
          max-tokens: ${OPENAI_MAX_TOKENS}
          top-p: ${OPENAI_TOP_P}

  doc:
    api-docs:
      enabled: true
    enable-kotlin: true
    swagger-ui:
      enabled: true
